M48
; DRILL file {KiCad 9.0.7} date 2026-04-23T19:43:10-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-23T19:43:10-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.500
%
G90
G05
T1
X138.391Y-54.33
T2
X80.163Y-35.048
X80.163Y-115.827
X138.573Y-35.048
X138.573Y-115.827
M30
