M48
; DRILL file {KiCad 9.0.7} date 2026-02-19T22:53:16-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-19T22:53:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.500
%
G90
G05
T1
X138.391Y-54.33
T2
X80.771Y-34.44
X80.771Y-115.22
X139.181Y-34.44
X139.181Y-115.22
M30
